### PR TITLE
Docker compose fix

### PR DESCRIPTION
**Pull request by darksidecat**

### CODE REVIEW

**Comment by MasterGroosha** [comment]
Thank you! Honestly I'd like to make more changes to docker-compose, like removing separate "volumes" section entirely.
Please note that the main development is done on my private GitLab repo, so I'd copy your changes and close this PR. Sorry for the inconvenience!

**Comment by darksidecat** [comment]
No problem, thanks :)

**Comment by MasterGroosha** [comment]
I'll keep this open for now until I fix this.

**Comment by MasterGroosha** [comment]
Fixed in ea866de47ed9b42448239b40282ed985f5212beb (along with other issues)

**Pull request closed without merging**
